#Numpy - Numerical Python
Used for array operations, linear algebra, statistics and more

In [1]:
!pip install numpy
#pip - python installing package

In [2]:
import numpy as np
#as - alias - nickname

In [3]:
a = np.array([10,20,30])

In [4]:
a

array([10, 20, 30])

#2d array

In [9]:
b = np.array([[10,20] , [40,50]])

In [8]:
b

array([[10, 20],
       [40, 50]])

In [12]:
c = np.array([[[1,2] , [3,4]] , [[5,6] , [7,8]]])

In [13]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

#Attributes
#check the dimensions - .ndim

In [15]:
a.ndim

1

In [16]:
b.ndim

2

In [17]:
c.ndim

3

In [18]:
d = np.array([[[1 , 2]]])

In [19]:
d

array([[[1, 2]]])

In [20]:
d.ndim

3

#shape - .shape

In [21]:
a.shape

(3,)

In [22]:
b.shape

(2, 2)

In [23]:
c.shape

(2, 2, 2)

In [24]:
d.shape

(1, 1, 2)

In [25]:
arr = np.array([[1,2,3] , [4,5,6]])

In [26]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

#size -- .size


In [27]:
arr.size

6

#.dtype

In [28]:
arr.dtype

dtype('int64')

In [30]:
arr1 = np.array([10,20,30], dtype = np.int16)

In [31]:
arr1

array([10, 20, 30], dtype=int16)

- int - whole no - int8, int16, int32, int64
- only positive - unsigned int - np.uint8, np.uint16, 32,
- float - decimal - float16, 16, 32,64
- bool - True False - np.bool_
- string - np.str_
- object - mix data type - np.object_

In [32]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr.T  # .T transpose the array

array([[1, 4],
       [2, 5],
       [3, 6]])

#Methods
# np.random.rand() - random float create between 0 and 1

In [34]:
np.random.rand()

0.9434846974413069

In [35]:
np.random.rand(3)

array([0.6182451 , 0.38232986, 0.54497569])

In [36]:
np.random.rand(2,3)

array([[0.28744073, 0.76635486, 0.74776065],
       [0.85474047, 0.57379969, 0.75768847]])

#np.random.randn() - create standard normal distribution
#where mean always = 0 and standard deviation = 1


In [37]:
np.random.randn(5)

array([-1.84995188,  1.43603839, -0.03832905, -0.29763088,  1.00127228])

In [38]:
np.random.randn(2,3)

array([[ 0.86753365,  0.04091464,  2.05619364],
       [-0.63108595, -0.44547113, -1.19941966]])

In [39]:
#random.randint()

In [40]:
np.random.randint(1,7)  #single random element bteween 1 to 6

6

In [42]:
np.random.randint(10)  # start from 0 - 9

8

In [43]:
np.random.randint(10 , size = 5)  #range 0 to 9

array([3, 0, 9, 6, 6])

#INDEXING AND SLICING

In [44]:
arr = np.array([10,20,30,40,50,60])

In [45]:
print(arr[-2])

50


In [46]:
print(arr[3])

40


In [47]:
arr1 = np.array([[10,20,30], [41,51,61]])

In [48]:
arr1

array([[10, 20, 30],
       [41, 51, 61]])

In [50]:
print(arr1[0][1]) #INDEXING

20


In [51]:
#SLICING

In [52]:
print(arr1[1,2])

61


In [53]:
print(arr1[0:2,1:3])

[[20 30]
 [51 61]]


#Aggregation functions

In [54]:
arr1

array([[10, 20, 30],
       [41, 51, 61]])

In [55]:
print(np.sum(arr1))

213


In [56]:
print(np.mean(arr1))

35.5


In [57]:
print(np.min(arr1))

10


In [58]:
print(np.std(arr1)) #standard deviation

17.519037264263886


In [59]:
print(np.var(arr1)) #variance

306.9166666666667


#.reshape

In [60]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [61]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
arr = np.array([1,2,3,4,5,6])

In [63]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])